---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)

dados = read_delim("https://www.stat.ubc.ca/~jenny/notOcto/STAT545A/examples/gapminder/data/gapminderDataFiveYear.txt")

dados_2007 = filter(dados, year == 2007) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
ggplot(dados_2007, aes(x=continent, y=lifeExp, fill=continent)) + 
  geom_boxplot() + scale_fill_brewer(palette = 'YlOrRd') +
  guides(fill = "none") + # Tirar Legenda 
  labs(title = "Expectativa de vida por continente", 
       subtitle = "Gap Minder 2007",
       x ="",
       y ="Expectativa de vida - em anos") 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
  ggplot(dados_2007, aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_point(size = 3, alpha=0.5) + 
    labs(title = "Expectativa de vida por continente", 
       subtitle = "Gap Minder 2007",
       x ="PIB per capita",
       y ="Expectativa de vida - em anos",
       color ="Continente") + theme_classic()
```

### Chart C

```{r}
tabela = table(dados_2007$continent)
tabela = data.frame(tabela)

degrade = colorRampPalette(c("darkblue", "lightblue"))
graf1 <- ggplot(tabela, aes(x="",y= Freq,fill = Var1))+
  geom_bar(stat="identity", width = 1)+
  scale_fill_manual(values=degrade(nrow(tabela)))+
  coord_polar("y",start = 0) + labs(fill = "Continente")
  graf1

```


